### ISSUE TITLE
0.4.7.0 - Playlists not loading

### ISSUE THREAD

**Issue by robotpukeko** [svbnet/Athame#147]
Attempting to load a playlist gives me one of two outcomes. Either nothing loads into the track list area with no feedback, or I get an error with the following info : 

[Window Title]
Athame

[Main Instruction]
An error occurred while trying to retrieve information for this media.

[Content]
The provided URL may be invalid or unsupported.

[^] Hide details  [OK]

[Expanded Information]
NullReferenceException: Object reference not set to an instance of an object.
--- Begin stack trace ---
   at Athame.UI.MainForm.AddToQueue(MusicService service, IMediaCollection item, String destination, String pathFormat)
   at Athame.UI.MainForm.<>c__DisplayClass46_0.<<button1_Click>b__0>d.MoveNext()

![image](https://user-images.githubusercontent.com/194367/38453049-79cdc742-3aa3-11e8-8399-f6b8d10bc630.png)

**Comment by fabriccioguzman** [comment]
at the moment playlist does not work in athame
