### ISSUE TITLE
Asset is not available.

### ISSUE THREAD

**Issue by alfablac** [svbnet/Athame#25]
Never saw this one. Occured with London Grammar albums.

[2017-06-08T16:20:02.4200853-03:00] [Error] MainForm: MDQ exception handlerOpenTidlException: Asset is not available in user's location
   at OpenTidl.OpenTidlClient.HandleResponse[T](RestResponse`1 response)
   at OpenTidl.Methods.OpenTidlSession.<GetTrackOfflineUrl>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AthamePlugin.Tidal.TidalService.<GetDownloadableTrackAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__29.MoveNext()

**Comment by svbnet** [comment]
What is the album ID, and what country are you in?

**Comment by alfablac** [comment]
https://listen.tidal.com/album/22878312
Is TIDAL georestricted? I see the same albums through different IPs.
Anyway, my account is from Brazil but I'm trying to grab it via a Canadian server

**Comment by svbnet** [comment]
Hmm, seems like it's been deleted from Tidal now. Perhaps a mistake on their part? Either way Tidal albums that are georestricted should return a 404 when you access them, but I think it depends on which country you are "in" when you sign in.
