### ISSUE TITLE
After the PC froze the app stopped to work

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [svbnet/Athame#34]
Windows 7 sp 1
.NET 4.6.2
Athame-0.4.3-base-plugins

After the PC froze (because of another app that sometimes works bad with threads), i relaunched PC and the app stopped to work. I tried to download athame again and re-setup .NET 4.6.2, but it didn't help. The message:
*System.NullReferenceException: Object reference not set to an instance of an object.
   at Athame.UI.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)*

I can click on a button to continue and then the main form is loaded, but if i try to drag-and-drop the form, i get the mistake again:

*System.NullReferenceException: Object reference not set to an instance of an object.
   at Athame.UI.MainForm.MainForm_Move(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnMove(EventArgs e)
   at System.Windows.Forms.Control.OnLocationChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)*

Or i can click on "Settings" and get the mistake:

*System.NullReferenceException: Object reference not set to an instance of an object.
   at Athame.UI.SettingsForm..ctor()
   at Athame.UI.MainForm.settingsToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)*

Now i just use Athame 0.4 that works without these mistakes.

**Comment by fabriccioguzman** [comment]
Mmm seems a common problem, try to delete the athame folder that is in appdata, roaming or local is that I am not sure which is left but there is this

Let me know if you want.

**Comment by fabriccioguzman** [comment]
Apparently, version 0.4.3 has problems downloading albums and this started from version 0.4.1 to me also happened to me

You also have to be calm, this project is in beta, lacks a lot and the only one who is working on this project is a single person, and we have to thank

**Comment by UserForTheOnlyTopic** [comment]
@fabriccioguzman your method helped me. Thank you!
You're right, @svbnet does great and helpful work, and we should appreciate that the creator lets us use the app and improves it. Thank you, @svbnet!
