### ISSUE TITLE
Album ... not found when it exists

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [svbnet/Athame#35]
I sometimes get the message:
*OpenTidl.Transport.OpenTidlException: Album [64424956] not found
    at OpenTidl.OpenTidlClient.HandleResponse[T](RestResponse`1 response)
    at OpenTidl.OpenTidlClient.<GetAlbum>d__2a.MoveNext()
--- ... ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Athame.TidalApi.TidalService.<GetAlbumAsync>d__19.MoveNext()
--- ... ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Athame.UI.MainForm.<>c__DisplayClass40_0.<<button1_Click>b__0>d.MoveNext()
--- ... ---
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)*

when i try to download some albums or tracks, the error isn't temporary, it appears for many days, for example, for the album 64424956. I can see the album in my profile, i can listen to it and can download it by another way, but not by the app.
The same problem with new albums on day of release when some countries can already get new albums and other can't yet, although i can see and listen to them, and download by another way, but the app returns such error (rarely other errors like when a tracklist is downloaded but every song has a red sign that it isn't unavailable).

**Comment by redreadnut** [comment]
> download by another way
what way? he he

**Comment by FatKiwi** [comment]
Can confirm about this one with different album.

OpenTidl.Transport.OpenTidlException: Album [73416053] not found
   at OpenTidl.OpenTidlClient.HandleResponse[T](RestResponse`1 response)
   at OpenTidl.OpenTidlClient.<GetAlbum>d__2a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AthamePlugin.Tidal.TidalService.<GetAlbumAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Athame.UI.MainForm.<>c__DisplayClass43_0.<<button1_Click>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by fabriccioguzman** [comment]
Mmm seems a common problem, try to delete the athame folder that is in appdata, roaming or local is that I am not sure which is left but there is this

Let me know if you want.

**Comment by fabriccioguzman** [comment]
Apparently version 0.4.3 has problems downloading albums and this started from version 0.4.1 to me also happened to me and what I do is copy the link of each music and I download it without problems but download M4a is Worse and is more problematic

You also have to be calm, this project is in beta, lacks a lot and the only one who is working on this project is a single person, and we have to thank

**Comment by UserForTheOnlyTopic** [comment]
@fabriccioguzman your method works. Thank you! New albums can't be tested at the moment but at the end of next work week it will be known, i assume it will work fine for them as well.

To other users with the same problem: i already removed my Athame folder from AppData so i can't help, but if you yet have the folder, your info from those files (without your personal data, of course) can help the creator to find the mistake, just put their content into some your message.

**Comment by FatKiwi** [comment]
The problem seems to be in SessionToken in TidalSettings.json
When you delete the old file and login again, new session is created and problem fixed. Weird, but it worked. So thanks for suggestions.

**Comment by svbnet** [comment]
^
