### ISSUE TITLE
[Tidal] An unknown error occurred. You might need to sign into this service again.

### ISSUE THREAD

**Issue by FatKiwi** [svbnet/Athame#45]
ID: 74818284
Volume 2, Track 7
Track name: 86

[Error] MainForm: PresentException
ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.EnsureVisible(Int32 index)
   at Athame.UI.MainForm.MediaDownloadQueue_TrackDequeued(Object sender, TrackDownloadEventArgs e)
   at Athame.DownloadAndTag.MediaDownloadQueue.OnTrackDequeued(TrackDownloadEventArgs e)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Athame.DownloadAndTag.MediaDownloadQueue.<StartDownloadAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Athame.UI.MainForm.<startDownloadButton_Click>d__53.MoveNext()

Signing again doesn't work.

**Comment by fabriccioguzman** [comment]
That strange, I manage to download without any problem, only using the link of that track only, do not use the link of the album

**Comment by svbnet** [comment]
The main queue listview implementation is really buggy, but rather than rewriting it I'm hoping to just make the next release the WPF version, which should fix most of the UI issues.
