### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by whatsupimr** [svbnet/Athame#69]
When I try to install the Tidal plugin, the Athame program opens with these 2 errors, back to back: 
![capture](https://user-images.githubusercontent.com/23161744/31572890-51fcaad2-b06d-11e7-87e2-42835f26d524.PNG)
![capture1](https://user-images.githubusercontent.com/23161744/31572891-54837920-b06d-11e7-81f4-d790fa9587e7.PNG)

What could I be doing wrong? My plugins folder is located in Athame_master/Athame/bin/Debug/Plugins. I have deleted the settings.json file in the AppData. I used Visual Studio 2017 to build it from the .csproj file. Any ideas? Thanks!

**Comment by svbnet** [comment]
does the same error occur when you download the latest release? can you post a log?

**Comment by svbnet** [comment]
(as in the prebuilt zip)

**Comment by whatsupimr** [comment]
Yup, I have both the latest release of Athame_master and of Tidal.zip. Where would I find a log?

**Comment by whatsupimr** [comment]
Nevermind, I found the folder the logs are supposed to be in. There is nothing in it.

**Comment by whatsupimr** [comment]
reply to

**Comment by whatsupimr** [comment]
Hey svbnet, can you walk me through the steps of building the .exe? Maybe I did something wrong along the way. Thanks!

**Comment by whatsupimr** [comment]
[2017-10-16T00:00:31.7751556-06:00] [Debug] Program: Logging installed on AppDomain
[2017-10-16T00:00:31.7871668-06:00] [Debug] SettingsFile: Init settings file
[2017-10-16T00:00:31.7881677-06:00] [Debug] SettingsFile: Load config
[2017-10-16T00:00:31.9247990-06:00] [Debug] Program: Ready to begin main form loop
[2017-10-16T00:00:32.0218918-06:00] [Error] PluginManager: While loading plugin 2.3
FileNotFoundException: Could not find file 'C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\Plugins\2.3\AthamePlugin.2.3.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Athame.Plugin.PluginManager.LoadAll() in C:\Users\Jonathan\Desktop\Athame-master\Athame\Plugin\PluginManager.cs:line 185
[2017-10-16T00:00:32.0254636-06:00] [Debug] PluginManager: Init plugin settings
[2017-10-16T00:00:34.1969591-06:00] [Debug] SettingsFile: Saving config to C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\UserDataDebug\Athame Settings.json
[2017-10-16T00:01:09.0177734-06:00] [Debug] Program: Logging installed on AppDomain
[2017-10-16T00:01:09.0292863-06:00] [Debug] SettingsFile: Init settings file
[2017-10-16T00:01:09.0302873-06:00] [Debug] SettingsFile: Load config
[2017-10-16T00:01:09.1574818-06:00] [Debug] Program: Ready to begin main form loop
[2017-10-16T00:01:09.2436712-06:00] [Error] PluginManager: While loading plugin 2.3
FileNotFoundException: Could not find file 'C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\Plugins\2.3\AthamePlugin.2.3.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Athame.Plugin.PluginManager.LoadAll() in C:\Users\Jonathan\Desktop\Athame-master\Athame\Plugin\PluginManager.cs:line 185
[2017-10-16T00:01:09.2446725-06:00] [Debug] PluginManager: Init plugin settings
[2017-10-16T00:01:14.2497538-06:00] [Debug] SettingsFile: Saving config to C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\UserDataDebug\Athame Settings.json

**Comment by whatsupimr** [comment]
There's the log you asked for a few days ago, sorry it took so long to reply. ^^^
