### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by whatsupimr** [svbnet/Athame#73]
![31572890-51fcaad2-b06d-11e7-87e2-42835f26d524](https://user-images.githubusercontent.com/23161744/31597486-d1770c8c-b205-11e7-87ec-353cb1ab2ad3.png)
![31572891-54837920-b06d-11e7-81f4-d790fa9587e7](https://user-images.githubusercontent.com/23161744/31597490-d33741ea-b205-11e7-845b-bd3dece7e20b.png)

[2017-10-16T00:00:31.7751556-06:00] [Debug] Program: Logging installed on AppDomain
[2017-10-16T00:00:31.7871668-06:00] [Debug] SettingsFile: Init settings file
[2017-10-16T00:00:31.7881677-06:00] [Debug] SettingsFile: Load config
[2017-10-16T00:00:31.9247990-06:00] [Debug] Program: Ready to begin main form loop
[2017-10-16T00:00:32.0218918-06:00] [Error] PluginManager: While loading plugin 2.3
FileNotFoundException: Could not find file 'C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\Plugins\2.3\AthamePlugin.2.3.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Athame.Plugin.PluginManager.LoadAll() in C:\Users\Jonathan\Desktop\Athame-master\Athame\Plugin\PluginManager.cs:line 185
[2017-10-16T00:00:32.0254636-06:00] [Debug] PluginManager: Init plugin settings
[2017-10-16T00:00:34.1969591-06:00] [Debug] SettingsFile: Saving config to C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\UserDataDebug\Athame Settings.json
[2017-10-16T00:01:09.0177734-06:00] [Debug] Program: Logging installed on AppDomain
[2017-10-16T00:01:09.0292863-06:00] [Debug] SettingsFile: Init settings file
[2017-10-16T00:01:09.0302873-06:00] [Debug] SettingsFile: Load config
[2017-10-16T00:01:09.1574818-06:00] [Debug] Program: Ready to begin main form loop
[2017-10-16T00:01:09.2436712-06:00] [Error] PluginManager: While loading plugin 2.3
FileNotFoundException: Could not find file 'C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\Plugins\2.3\AthamePlugin.2.3.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Athame.Plugin.PluginManager.LoadAll() in C:\Users\Jonathan\Desktop\Athame-master\Athame\Plugin\PluginManager.cs:line 185
[2017-10-16T00:01:09.2446725-06:00] [Debug] PluginManager: Init plugin settings
[2017-10-16T00:01:14.2497538-06:00] [Debug] SettingsFile: Saving config to C:\Users\Jonathan\Desktop\Athame-master\Athame\bin\Debug\UserDataDebug\Athame Settings.json

There's the log you asked for a few days ago. I figured I would start a new issue since the other one was sloppy. Thanks!

**Comment by svbnet** [comment]
The parent folder needs to be the same name as the plugin's name, as plugins are loaded like:
`(Name)\AthamePlugin.(Name).dll`
