### ISSUE TITLE
Playlist can't be imported if playlist "SaveDirectory" is set to other directory

### ISSUE THREAD

**Issue by vBm** [svbnet/Athame#98]
Not exactly sure if this should be reported here or [downstream](https://github.com/TripleFrequency/AthamePlugin.Deezer). I guess it should be reported here because if "playlist download option" is set to be the "same as album/track" this doesn't happen. If, on the other hand we use some defined folder we get this error. Note that same issue happens on default settings but as soon as we enable "same as album/track" option, error is gone and we can successfully import the playlist.

Content of `Athame Settings.json`
```
{
  "AlbumArtworkSaveFormat": 1,
  "GeneralSavePreference": {
    "SaveDirectory": "C:\\Users\\vBm\\Downloads\\Athame",
    "SaveFormat": "{AlbumArtistOrArtist} - {Album.Title}/{TrackNumber} {Title}",
    "AskForLocation": false
  },
  "PlaylistSavePreference": {
    "SaveDirectory": "C:\\Users\\vBm\\Downloads\\Athame",
    "SaveFormat": "{PlaylistName}",
    "AskForLocation": false
  },
  "PlaylistSavePreferenceUsesGeneral": false,
  "MainWindowPreference": {
    "Location": "548, 70",
    "Size": "823, 858"
  }
}
```

I'm on Win10 FCU with .NET Framework 4.7.1

```
[Main Instruction]
An error occurred while trying to retrieve information for this media.

[Content]
The provided URL may be invalid or unsupported.

[Expanded Information]
KeyNotFoundException: The given key was not present in the dictionary.
--- Begin stack trace ---
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CenterCLR.Named.<>c__DisplayClass16_0.<Format>b__0(String key)
   at CenterCLR.Named.GetValueBySelector(Func`2 selector, String dotNotatedKey)
   at CenterCLR.Named.WriteFormat(TextWriter tw, String format, Func`2 selector)
   at CenterCLR.Named.Format(String format, Func`2 selector)
   at CenterCLR.Named.Format(String format, Dictionary`2 keyValues)
   at Athame.Utils.TrackFileExtensions.GetBasicPath(Track track, String pathFormat, Dictionary`2 vars)
   at Athame.UI.MainForm.AddToQueue(MusicService service, IMediaCollection item, String destination, String pathFormat)
   at Athame.UI.MainForm.<>c__DisplayClass46_0.<<button1_Click>b__0>d.MoveNext()
```

Playlist in question is this one. https://www.deezer.com/en/playlist/1283499335
On the other hand, any playlist will show the same error.
Couldn't test Google Play nor Tidal since they're not available in my country.

**Comment by vBm** [comment]
It seems this is similar to #74.
If it's the same issue, sorry for opening a duplicate.

**Comment by svbnet** [comment]
You need to replace `{PlaylistName}` with `{ServiceName}`.

**Comment by vBm** [comment]
@svbnet Doesn't change the error.
